2017-08-24 16:48:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Conversión de datos fallida, convirtiendo "'' (SYS_SECCION: SESION INT)"
Data conversion error converting "'' (SYS_SECCION: SESION INT)"; SQL statement:
INSERT INTO SYS_Seccion (SeccionID, Seccion, SubSeccion, Formulario, Modulo, Sesion) VALUES (33, 'Taxonomi', 'Vegetacion Mayor morfotipos creciendo de manera gregaria', 'vegetacionMayorG', 'H', '') -- (33, 'Taxonomi', 'Vegetacion Mayor morfotipos creciendo de manera gregaria', 'vegetacionMayorG', 'H', '') [22018-196]
2017-08-24 16:52:25 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/ignacio.martinez/Desktop/appCONAFOR/AppMuestreoINF/dist/MuestreoINF_2017.mv.db [1.4.192/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/ignacio.martinez/Desktop/appCONAFOR/AppMuestreoINF/dist/MuestreoINF_2017.mv.db [1.4.192/7]" [50000-192]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:375)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:358)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2893)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2463)
	at org.h2.engine.Database.open(Database.java:692)
	at org.h2.engine.Database.openDatabase(Database.java:270)
	at org.h2.engine.Database.<init>(Database.java:264)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:102)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at gob.conafor.conn.dat.LocalConnection.getConnection(LocalConnection.java:58)
	at gob.conafor.sys.mod.CDSecuencia.habilitarCapturaSitio(CDSecuencia.java:131)
	at gob.conafor.ini.vie.FrmInicio.<init>(FrmInicio.java:29)
	at gob.conafor.ini.vie.Main.main(Main.java:19)
Caused by: org.h2.jdbc.JdbcSQLException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/ignacio.martinez/Desktop/appCONAFOR/AppMuestreoINF/dist/MuestreoINF_2017.mv.db [1.4.192/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/ignacio.martinez/Desktop/appCONAFOR/AppMuestreoINF/dist/MuestreoINF_2017.mv.db [1.4.192/7]" [50000-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 27 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/ignacio.martinez/Desktop/appCONAFOR/AppMuestreoINF/dist/MuestreoINF_2017.mv.db [1.4.192/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:344)
	... 22 more
2017-08-24 16:52:34 jdbc[13]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-192]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:129)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:102)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at gob.conafor.conn.dat.LocalConnection.getConnection(LocalConnection.java:58)
	at gob.conafor.taxonomia.mod.CDCondicionTaxonomica.getVigorSotobosqueRepoblado(CDCondicionTaxonomica.java:52)
	at gob.conafor.taxonomia.vie.FrmSotoBosque.fillCmbVigor(FrmSotoBosque.java:389)
	at gob.conafor.taxonomia.vie.FrmSotoBosque.<init>(FrmSotoBosque.java:91)
	at gob.conafor.upm.vie.UPMForms.<clinit>(UPMForms.java:47)
	at gob.conafor.ini.vie.FrmInicio.<init>(FrmInicio.java:37)
	at gob.conafor.ini.vie.Main.main(Main.java:19)
Caused by: org.h2.jdbc.JdbcSQLException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 16 more
2017-08-24 16:57:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Error de Sintaxis en sentencia SQL "                             
CREATE TABLE BRIGADA_BRIGADISTAS (BRIGADISTAID INTEGER PRIMARY KEY ASC[*] AUTOINCREMENT, NOMBRE VARCHAR (100), APELLIDOPATERNO VARCHAR (100), APELLIDOMATERNO VARCHAR (100), PUESTOID INT, ACTIVO INT, EMPRESAID INTEGER) "; se esperaba "HASH, AUTO_INCREMENT, NOT, NULL, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "                             
CREATE TABLE BRIGADA_BRIGADISTAS (BRIGADISTAID INTEGER PRIMARY KEY ASC[*] AUTOINCREMENT, NOMBRE VARCHAR (100), APELLIDOPATERNO VARCHAR (100), APELLIDOMATERNO VARCHAR (100), PUESTOID INT, ACTIVO INT, EMPRESAID INTEGER) "; expected "HASH, AUTO_INCREMENT, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
-- Table: BRIGADA_Brigadistas
CREATE TABLE BRIGADA_Brigadistas (BrigadistaID INTEGER PRIMARY KEY ASC AUTOINCREMENT, Nombre VARCHAR (100), ApellidoPaterno VARCHAR (100), ApellidoMaterno VARCHAR (100), PuestoID INT, Activo INT, EmpresaID INTEGER) [42001-196]
2017-08-24 16:59:19 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/ignacio.martinez/Desktop/appCONAFOR/AppMuestreoINF/dist/MuestreoINF_2017.mv.db [1.4.192/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/ignacio.martinez/Desktop/appCONAFOR/AppMuestreoINF/dist/MuestreoINF_2017.mv.db [1.4.192/7]" [50000-192]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:375)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:358)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2893)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2463)
	at org.h2.engine.Database.open(Database.java:692)
	at org.h2.engine.Database.openDatabase(Database.java:270)
	at org.h2.engine.Database.<init>(Database.java:264)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:102)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at gob.conafor.conn.dat.LocalConnection.getConnection(LocalConnection.java:58)
	at gob.conafor.sys.mod.CDSecuencia.habilitarCapturaSitio(CDSecuencia.java:131)
	at gob.conafor.ini.vie.FrmInicio.<init>(FrmInicio.java:29)
	at gob.conafor.ini.vie.Main.main(Main.java:19)
Caused by: org.h2.jdbc.JdbcSQLException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/ignacio.martinez/Desktop/appCONAFOR/AppMuestreoINF/dist/MuestreoINF_2017.mv.db [1.4.192/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/ignacio.martinez/Desktop/appCONAFOR/AppMuestreoINF/dist/MuestreoINF_2017.mv.db [1.4.192/7]" [50000-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 27 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/ignacio.martinez/Desktop/appCONAFOR/AppMuestreoINF/dist/MuestreoINF_2017.mv.db [1.4.192/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:344)
	... 22 more
2017-08-24 16:59:27 jdbc[13]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-192]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:129)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:102)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at gob.conafor.conn.dat.LocalConnection.getConnection(LocalConnection.java:58)
	at gob.conafor.taxonomia.mod.CDCondicionTaxonomica.getVigorSotobosqueRepoblado(CDCondicionTaxonomica.java:52)
	at gob.conafor.taxonomia.vie.FrmSotoBosque.fillCmbVigor(FrmSotoBosque.java:389)
	at gob.conafor.taxonomia.vie.FrmSotoBosque.<init>(FrmSotoBosque.java:91)
	at gob.conafor.upm.vie.UPMForms.<clinit>(UPMForms.java:47)
	at gob.conafor.ini.vie.FrmInicio.<init>(FrmInicio.java:37)
	at gob.conafor.ini.vie.Main.main(Main.java:19)
Caused by: org.h2.jdbc.JdbcSQLException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 16 more
2017-08-24 17:56:48 jdbc[45]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-192]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:129)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:102)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at gob.conafor.c.a.b.a(Unknown Source)
	at gob.conafor.i.a.i.a(Unknown Source)
	at gob.conafor.i.c.aj.d(Unknown Source)
	at gob.conafor.i.c.aj.<init>(Unknown Source)
	at gob.conafor.i.c.cs.<clinit>(Unknown Source)
	at gob.conafor.i.c.aj.<init>(Unknown Source)
	at gob.conafor.j.b.aw.<clinit>(Unknown Source)
	at gob.conafor.ini.vie.F.<init>(Unknown Source)
	at gob.conafor.ini.vie.Main.main(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 18 more
2017-08-25 10:11:15 jdbc[45]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-192]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:129)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:102)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at gob.conafor.c.a.b.a(Unknown Source)
	at gob.conafor.i.a.i.a(Unknown Source)
	at gob.conafor.i.c.aj.d(Unknown Source)
	at gob.conafor.i.c.aj.<init>(Unknown Source)
	at gob.conafor.i.c.cs.<clinit>(Unknown Source)
	at gob.conafor.i.c.aj.<init>(Unknown Source)
	at gob.conafor.j.b.aw.<clinit>(Unknown Source)
	at gob.conafor.ini.vie.F.<init>(Unknown Source)
	at gob.conafor.ini.vie.Main.main(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 18 more
2017-08-25 12:40:20 jdbc[45]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-192]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:129)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:102)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at gob.conafor.c.a.b.a(Unknown Source)
	at gob.conafor.i.a.i.a(Unknown Source)
	at gob.conafor.i.c.aj.d(Unknown Source)
	at gob.conafor.i.c.aj.<init>(Unknown Source)
	at gob.conafor.i.c.cs.<clinit>(Unknown Source)
	at gob.conafor.i.c.aj.<init>(Unknown Source)
	at gob.conafor.j.b.aw.<clinit>(Unknown Source)
	at gob.conafor.ini.vie.F.<init>(Unknown Source)
	at gob.conafor.ini.vie.Main.main(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 18 more
2017-08-25 14:24:02 jdbc[47]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-192]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:129)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:102)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at gob.conafor.c.a.b.a(Unknown Source)
	at gob.conafor.i.a.c.e(Unknown Source)
	at gob.conafor.i.c.aj.f(Unknown Source)
	at gob.conafor.i.c.aj.<init>(Unknown Source)
	at gob.conafor.i.c.cs.<clinit>(Unknown Source)
	at gob.conafor.i.c.aj.<init>(Unknown Source)
	at gob.conafor.j.b.aw.<clinit>(Unknown Source)
	at gob.conafor.ini.vie.F.<init>(Unknown Source)
	at gob.conafor.ini.vie.Main.main(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 18 more
